### ISSUE TITLE
How can I save images as a raw format?

### ISSUE THREAD

**Issue by UdonDa** [yzxing87/Invertible-ISP#3]
I read your impressive paper and am interested in your work.

I ask you how to save the predicted images in a raw format.
In your implementation, you save it in a jpg format.
https://github.com/yzxing87/Invertible-ISP/blob/main/test_raw.py#L104

Please share the code of saving in raw format.

**Comment by yzxing87** [comment]
Hi, we actually save predicted raw in .npy format, as shown in [this line](https://github.com/yzxing87/Invertible-ISP/blob/main/test_raw.py#L108). JPEG format is just used for visualization purpose. And I don't think there is any existing python library to save an array into raw format. Adobe RAW SDK may provide the utility to save an array into DNG format, but it is based on C or C++.

**Comment by UdonDa** [comment]
Thank you for teaching me!

**Comment by xunmeibuyue** [comment]
In fact, [PiDNG](https://github.com/schoolpost/PiDNG) can do part of this work, but it aims at Raspberry Pi camera.  
However, I failed to port the code on other type of camera.
Sad.
