### ISSUE TITLE
color shift problem

### ISSUE THREAD

**Issue by StephanPan** [yzxing87/Invertible-ISP#8]

**Comment by StephanPan** [comment]
i met the color shift problem that when i use customed rgb image to reconstruct the raw image, the result will dominate by one channel. After reversing demosaicing refering to "unprocessing", the color of img is shifted to the aforementioned channel.
![image](https://user-images.githubusercontent.com/37864281/130548635-e1d0fb0e-139e-4853-bd48-fe6e9588de96.png)

**Comment by yzxing87** [comment]
Hi, I am not sure if I understand the 'color shift problem' correctly. But have you 'unprocess' the white balance before you reverse the demosaicing step? My another guess is your raw data may not be the 'RGGB' pattern. You can check your exif file. It would be helpful if you can post the wrong results here.
